### PR TITLE
Optional enabling of AIML fallback

### PR DESCRIPTION
**Pull request by nielstron**
This patch enables the user to control whether or not the chatbot fallback should be used. According settings will be shown on home.mycroft.ai.
The brain then only will be loaded when the chatbot fallback is enabled.
This is only a slightly varied fork of #4

### CODE REVIEW

**Comment by nielstron** [comment]
I changed the brain save path to brain/bot_brain.brn, so that the skill will not reload on save

**Comment by MB2412** [comment]
@nielstron @forslund @JarbasAI thanks guys for your efforts
 I don't understand why this skill does not work for me,
 I generated the brain file after changing init_py like @nielstron requested
 I previously tried to run a chatbot based on email files in ROS (robotic operating system) and it works offline perfect 
In Mycroft it every time I start it, I have this warning
aiml

**Comment by nielstron** [comment]
@MB2412 Please open an issue for this. If you do so, you may directly include my answer in it:

The brain file of your skill is still located on the top level of the skill directory. It should rather be in some subdir like `brain/`. Delete the old brainfile and change the load path in the init to `./brain/bot_brain.brn`.

If the brain is stored on the highest level of the skill, this causes mycroft to think the skill got updated and thus reloading the skill, ultimately resulting in a crash everytime the brain is loaded or stored.

**Comment by forslund** [comment]
Merged through #11.

Sorry for the delay with this. It's merged now, a big thank you for all your work.

**Pull request closed without merging**
